### ISSUE TITLE
Support preview feature

### ISSUE THREAD

**Issue by nrempel** [TryGhost/gatsby-starter-ghost#30]
Hi there,

Is it possible to query the content API to include drafts in the posts request? I would like to support the preview feature offered by the admin dashboard.

I notice there is no mention of drafts here: https://docs.ghost.org/api/content/#posts

But there is mention of drafts here: https://api.ghost.org/docs/posts

Does anyone know if this is currently possible?

Thanks!

**Comment by nrempel** [comment]
I dug around in the source code a bit and as far as I can tell, this is not currently possible. (Please correct me if I'm wrong!)

I have made a proposal on the forum to support this use case: https://forum.ghost.org/t/allow-querying-drafts-from-content-api-by-id-only/5443

**Comment by AileenCGN** [comment]
Hey there @nrempel 👋 

Sorry for the delay 😔 

You are right, because we're using the Content API in the [Ghost source plugin](https://github.com/TryGhost/gatsby-source-ghost), we're currently not able to get preview links.

The best way currently is exactly what you did: opening a forum topic so people can vote on that one.

That being said, I'm closing this issue now, as we only keep issues open for bug reports.
