### ISSUE TITLE
Error: cheerio.load() expects a string

### ISSUE THREAD

**Issue by rtuRgALp** [TryGhost/gatsby-starter-ghost#379]
### Issue Summary

Error `cheerio.load() expects a string` occurs when deploying gatsby-starter-ghost fork to Netlify. I wasn't encountering this error previously, but after a [fresh install](https://github.com/luisvargasio/luisvargaspw) I am seeing this error. [Here's](https://pastebin.com/tuWARSTh) the error in the deploy log from Netlify.

### To Reproduce

1. Fork tryghost/gatsby-starter-ghost
2. Update siteConfig.js to point to valid UEL (not localhost)
3. Update .ghost.json with API URL and Content API key
4. Create new site in Netlify from forked repo && deploy site

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 4.6.4
* OS: macOS X 10.15.5

**Comment by gjdickens** [comment]
I was just having this issue - for me it turned out that I had internal posts that were crashing my RSS feed generation on build. (since the Ghost content API returns 'null' html when posts are set to internal visibility)  So I had to modify my GraphQL query in src/utils/rss/generate-feed.js to filter out internal posts.

Full code in this commit: https://github.com/epilocal/newsliner-gatsby/commit/8bdc0913f7e6e2b72ac81fc3ac8830e6fc5384a6
