### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by yoonwaiyan** [TryGhost/gatsby-starter-ghost#54]
Hi, not sure if this is related to the Ghost GraphQL request. This is the first time I'm setting up Gatsby for my Ghost blog. I've cloned locally and run `$gatsby develop` but I've received this error message: `TypeError: Cannot read property 'node' of undefined` in several React components. This is weird because using the default Ghost config works but it didn't work after changing the config to my Ghost credentials (the post listing is ok after `console.log` within PostCard component but the components are not rendered). Any idea? Is it because I'm using older version of Ghost (It's self hosted)?

<img width="1119" alt="Screen Shot 2019-05-11 at 8 19 13 PM" src="https://user-images.githubusercontent.com/3081772/57569612-161da200-742a-11e9-9f7e-d2374f082f73.png">

**Comment by AileenCGN** [comment]
> Any idea? Is it because I'm using older version of Ghost (It's self hosted)?

This will most probably be the issue here. It's impossible to help debugging this, without further information. You will need to be at least at Ghost `2.22.0`, see [here](https://github.com/TryGhost/Ghost/commit/5d977f23d40dc2fe32f7886314348f06ad260906)

Please refer to our https://forum.ghost.org for further questions, as we keep GitHub issues only open for bugs 😊

**Comment by defel** [comment]
FYI
I got this error in Ghost 2.10.x and (current) 2.23.x - reason for me was a trailing slash behind the hostname, which was found fast, as there is an error on the console: 

> Error: GhostContentAPI Config Invalid: @tryghost/content-api requires a "url" without a trailing slash like "https://site.com" or "https://site.com/blog"

:ok_hand:
