### ISSUE TITLE
vulnerability found in lodash

### ISSUE THREAD

**Issue by mskian** [TryGhost/gatsby-starter-ghost#67]
vulnerability found in `…/gatsby-plugin-ghost-manifest/yarn.lock`

**Comment by AileenCGN** [comment]
Can you provide more information? The issue template explicitly asks you to do so.

**Comment by mskian** [comment]
![Screenshot from 2019-07-16 09-04-09](https://user-images.githubusercontent.com/10300271/61264047-b5537280-a7a8-11e9-957f-2fb3a04a0887.png)

**Comment by mskian** [comment]
also in `@tryghost/helpers@1.1.6` Affected dependencies ` lodash-es` Latest patched Version `4.17.14`

![Screenshot from 2019-07-16 09-08-31](https://user-images.githubusercontent.com/10300271/61264208-4aef0200-a7a9-11e9-87f9-50e4c929beca.png)

`

**Comment by AileenCGN** [comment]
Well, you can see that this is happening in an upstream provider in babel who needs to update `lodash`. There's nothing we can do about this here in this repository.

Our lodash dependency is up to date: https://github.com/TryGhost/gatsby-starter-ghost/blob/master/package.json#L52

And the same applies to `@tryghost/helpers`. This needs to be updated in that specific repository. Why are you opening the issue here?

**Comment by mskian** [comment]
Sorry Actually I got Notifications From Github 
I just want to Share 
Anyways `gatsby-plugin-ghost-manifest` Plugin Need to Update the Deps 
Seems `@babel/generator` `@babel/core` `@babel/generator `@babel/cli` Released the patched

**Comment by AileenCGN** [comment]
Yeah, that's true. I just did that, but it didn't seem like it was resolved then. Still getting the warnings about lodash in babel. Will update the deps in the next days and check if they updated upstream.

Anyway, thanks for the report, I didn't want to sound too harsh, but it's always better to provide as much information as possible, just like you did in your last comment 😊

**Comment by AileenCGN** [comment]
Updated the deps with https://github.com/TryGhost/gatsby-starter-ghost/commit/c4653e7499fd8b3099727a2555aaf395f59112a3
