### ISSUE TITLE
RSS feed icon links to gatsby.ghost feed, not to blog feed

### ISSUE THREAD

**Issue by namdnguyen** [TryGhost/gatsby-starter-ghost#69]
### Issue Summary

The RSS icon does not point to my blog's RSS feed, but to the gatsby-starter-ghost feed. Ghost is self-hosted on AWS EC2 and deployed to https://homads-blog.netlify.com/ with Netflify using build command `gatsby build` from Bitbucket repo.

### To Reproduce

1. `.ghost.json` development set to https://gatsby.ghost.io and production set to
https://ghost.homads.com.
2. Ghost set to private mode.
3. Netlify-Ghost integration configured for `Site changed (rebuild)`.

I expected the RSS icon to point to a https://ghost.homads.com/rss feed. I've confirmed that Netlify rebuilds site from both git commits and changes within Ghost.

https://homads-blog.netlify.com/rss is generated and looks mostly correct, except it shows the site address as https://homads-blog.netlify.com/rss at the top. Posts URLs are correct, however.

I've also tried setting both development and production in my local .ghost.json to point to ghost.homads.com and testing with `gatsby develop` and `gatsby build && gatsby serve`, which has the same issues mentioned above.

### Technical details:

* Ghost Version: 2.25.6
* Gatsby Version: 2.13.3
* Gatsby CLI Version: 2.7.14
* Node Version: 10.16.0
* OS: Ubuntu 18.04.2 LTS (local development)
* OS: Ubuntu 18.04.2 LTS (Ghost production on AWS)
* OS: Ubuntu 16.04 (Netlify)

**Comment by AileenCGN** [comment]
@namdnguyen this is fully intentional. The RSS feed needs to be served from your Gatsby site, which is the one being crawled by feed readers and search engines. The Ghost starter actually comes with a RSS feed generator installed, see [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/80a4d7902aa49eca0e8edb7d12f9e20e3d12160c/gatsby-config.js#L92-L93).

You can see, how this is working for https://gatsby.ghost.org, which is setup in the same way and is the deployment of the master branch of this repository: https://gatsby.ghost.org/rss
